controller_list:
  - name: fake_manipulator_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
initial:  # Define initial robot poses.
  - group: manipulator
    pose: all-zeros
