# This config uses industrial_ci (https://github.com/ros-industrial/industrial_ci.git).
# For troubleshooting, see readme (https://github.com/ros-industrial/industrial_ci/blob/master/README.rst)

name: pre-release

on:
  workflow_dispatch:
    inputs:
      ROS_DISTRO:
        type: string
        required: true
        description: 'ROS distribution codename:'
        default: rolling

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  default:
    env:
      ROS_DISTRO: ${{ inputs.ROS_DISTRO }}
      PRERELEASE: true
      BASEDIR: ${{ github.workspace }}/.work

    name: "${{ inputs.ROS_DISTRO }}"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ros-industrial/industrial_ci@master
